name: Python Docker Action

on: push

jobs:
  run-python:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - name: Ver version de Python
        run: python --version

      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar app
        run: python app.py